openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-n7fv.onrender.com
paths:
  /contacts/{id}:
    get:
       $ref: '../swager/paths/contacts/{id}/get.yaml'
    delete:
      $ref: '../swager/paths/contacts/{id}/delete.yaml'
    patch:
      $ref: '../swager/paths/contacts/{id}/patch.yaml'
  /contacts:
    get:
      $ref: '../swager/paths/contacts/get.yaml'
    post:
      $ref: '../swager/paths/contacts/post.yaml'
  /auth/register:
    post:
      $ref: '../swager/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swager/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swager/paths/auth/logout.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swager/paths/auth/sendResetEmail.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swager/paths/auth/resetPwd.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
